export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORIES = "CREATE_CATEGORIES";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
